name: Multiple job
on: 
  push:
    branches:
      - 'main'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start job1"
      - run: sleep 3
      - run: date
      - run: echo "complete job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start job2"
      - run: date
      - run: echo "complete job2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start job3"
      - run: date
      - run: echo "complete job3"
  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start job4"
      - run: date
      - run: echo "complete job4"
